[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
testpaths = tests
env =
    DB_NAME=logiflow_test
    DB_HOST=localhost
    S3_ENDPOINT_URL=http://localhost:8333
    S3_ACCESS_KEY=any
    S3_SECRET_KEY=any
    S3_BUCKET_NAME=logiflow-test-bucket
    S3_REGION=us-east-1

