"""create users table

Revision ID: 79dd40b0cce8
Revises:
Create Date: 2026-04-20 17:16:01.865848

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "79dd40b0cce8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
