"""update_user_roles_and_cors

Revision ID: dc44969cffc5
Revises: a283d016c91f
Create Date: 2026-04-22 00:27:42.114274

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc44969cffc5"
down_revision: Union[str, Sequence[str], None] = "a283d016c91f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=8),
            type_=sa.Enum(
                "CLIENT",
                "DRIVER",
                "MANAGER",
                name="userrole",
                native_enum=False,
            ),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.Enum(
                "CLIENT",
                "DRIVER",
                "MANAGER",
                name="userrole",
                native_enum=False,
            ),
            type_=sa.VARCHAR(length=8),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
