services:
  db:
    image: postgres:17-alpine
    container_name: logiflow_db
    restart: always
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: logiflow_backend
    restart: always
    depends_on:
      - db
    env_file:
      - ../.env
    ports:
      - "8000:8000"

volumes:
  postgres_data:
